### PR TITLE
Don't intercept touch event on Tooltip layout

### PR DESCRIPTION
**Pull request by ghost**
This PR doesn't change behaviour how `Toolbar` dismissing works. Difference is that all touch events are passed to views bellow `Toolbar` without intercepting touch. IMO this gives much nicer UX when user don't have to press twice.

If you want to keep that mandatory click to dismiss Toolbar, then just say and I will change PR.

### CODE REVIEW

**Comment by ghost** [comment]
Friendly ping

**Comment by dvdrlee** [comment]
@jayrambhia can we please get this fix released into a version 1.6 ?

**Comment by dvdrlee** [comment]
Hey @jayrambhia this is major a UX improvement that we'd like to incorporate into our app, can we get a new release out please?

**Comment by jayrambhia** [comment]
Hi @audriusKV @dvdrlee, after testing this change, I realized that it does not improve UX and in fact it makes it weird. Due to this, as soon as the user touches anywhere, the tooltip will get dismissed. It does not matter if the user lifted the finger or not. So I'm going to spend couple of days trying to find a workaround in which the tooltip will intercept events and also pass the events to the parent view. If I don't find a solution I will clean up this commit from master.

**Pull request merged**
